"use client"

import * as React from "react"
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Loader2 } from "lucide-react"
import { toast } from "sonner"
import { RecurringScheduleData } from "./recurring-card"

interface RecurringDeleteModalProps {
  isOpen: boolean
  onClose: () => void
  onSuccess: () => void
  schedule: RecurringScheduleData | null
}

export function RecurringDeleteModal({
  isOpen,
  onClose,
  onSuccess,
  schedule,
}: RecurringDeleteModalProps) {
  const [isDeleting, setIsDeleting] = React.useState(false)

  const handleDelete = async () => {
    if (!schedule) return
    setIsDeleting(true)
    try {
      const res = await fetch(`/api/recurring-transactions/${schedule.id}`, {
        method: "DELETE",
      })

      if (!res.ok) {
        const err = await res.json()
        throw new Error(err.message || "Failed to delete schedule")
      }

      toast.success("Recurring schedule deleted successfully")
      onSuccess()
      onClose()
    } catch (err: any) {
      toast.error(err.message || "Failed to delete schedule")
    } finally {
      setIsDeleting(false)
    }
  }

  return (
    <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Delete Recurring Schedule</DialogTitle>
          <DialogDescription>
            Are you sure you want to remove{" "}
            <span className="font-semibold text-foreground">{schedule?.description}</span>? Past
            transactions generated by this schedule will remain safely in your ledger.
          </DialogDescription>
        </DialogHeader>

        <DialogFooter className="gap-2 sm:gap-0 pt-2">
          <Button type="button" variant="outline" onClick={onClose} disabled={isDeleting}>
            Cancel
          </Button>
          <Button type="button" variant="destructive" onClick={handleDelete} disabled={isDeleting}>
            {isDeleting && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
            Delete Schedule
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
